version: '3'

services:
    sonarqube:
        build: .
        ports:
            - 9000:9000
        environment:
            sonar.jdbc.username: sonar
            sonar.jdbc.password: sonar
            sonar.jdbc.url: jdbc:postgresql://db:5432/sonar
        depends_on:
            - db
    
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: sonar
            POSTGRES_USER: sonar
            POSTGRES_DB: sonar
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - /pg_data2:/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
